apiVersion: v2
appVersion: "development"
description: A Helm chart for Unleasherator CRDs
maintainers:
  - email: "nais@nav.no"
    name: "nais"
name: unleasherator-crds
type: application
version: 1.14.0
